python3 line-chart.py \
  -d mysql_macro.tsv \
  -o mysql_macro.pdf \
  --ylabel "Latency (ms)" \
  --xlabel "Number of Machines" \
  --logy  \
  --ymin 10 \
  --ymax 500000000 \
  --xmin 1 \
  --xmax 5 \
  --xscale 1 \
  --yscale 1 \
  --legendpos 'upper-right'
