/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MDTrieShard.h"
#include "MDTrieShard.tcc"




MDTrieShard_ping_args::~MDTrieShard_ping_args() noexcept {
}


MDTrieShard_ping_pargs::~MDTrieShard_ping_pargs() noexcept {
}


MDTrieShard_ping_result::~MDTrieShard_ping_result() noexcept {
}


MDTrieShard_ping_presult::~MDTrieShard_ping_presult() noexcept {
}


MDTrieShard_insert_args::~MDTrieShard_insert_args() noexcept {
}


MDTrieShard_insert_pargs::~MDTrieShard_insert_pargs() noexcept {
}


MDTrieShard_insert_result::~MDTrieShard_insert_result() noexcept {
}


MDTrieShard_insert_presult::~MDTrieShard_insert_presult() noexcept {
}


MDTrieShard_insert_for_latency_args::~MDTrieShard_insert_for_latency_args() noexcept {
}


MDTrieShard_insert_for_latency_pargs::~MDTrieShard_insert_for_latency_pargs() noexcept {
}


MDTrieShard_insert_for_latency_result::~MDTrieShard_insert_for_latency_result() noexcept {
}


MDTrieShard_insert_for_latency_presult::~MDTrieShard_insert_for_latency_presult() noexcept {
}


MDTrieShard_check_args::~MDTrieShard_check_args() noexcept {
}


MDTrieShard_check_pargs::~MDTrieShard_check_pargs() noexcept {
}


MDTrieShard_check_result::~MDTrieShard_check_result() noexcept {
}


MDTrieShard_check_presult::~MDTrieShard_check_presult() noexcept {
}


MDTrieShard_range_search_args::~MDTrieShard_range_search_args() noexcept {
}


MDTrieShard_range_search_pargs::~MDTrieShard_range_search_pargs() noexcept {
}


MDTrieShard_range_search_result::~MDTrieShard_range_search_result() noexcept {
}


MDTrieShard_range_search_presult::~MDTrieShard_range_search_presult() noexcept {
}


MDTrieShard_primary_key_lookup_args::~MDTrieShard_primary_key_lookup_args() noexcept {
}


MDTrieShard_primary_key_lookup_pargs::~MDTrieShard_primary_key_lookup_pargs() noexcept {
}


MDTrieShard_primary_key_lookup_result::~MDTrieShard_primary_key_lookup_result() noexcept {
}


MDTrieShard_primary_key_lookup_presult::~MDTrieShard_primary_key_lookup_presult() noexcept {
}


MDTrieShard_primary_key_lookup_path_args::~MDTrieShard_primary_key_lookup_path_args() noexcept {
}


MDTrieShard_primary_key_lookup_path_pargs::~MDTrieShard_primary_key_lookup_path_pargs() noexcept {
}


MDTrieShard_primary_key_lookup_path_result::~MDTrieShard_primary_key_lookup_path_result() noexcept {
}


MDTrieShard_primary_key_lookup_path_presult::~MDTrieShard_primary_key_lookup_path_presult() noexcept {
}


MDTrieShard_primary_key_lookup_binary_args::~MDTrieShard_primary_key_lookup_binary_args() noexcept {
}


MDTrieShard_primary_key_lookup_binary_pargs::~MDTrieShard_primary_key_lookup_binary_pargs() noexcept {
}


MDTrieShard_primary_key_lookup_binary_result::~MDTrieShard_primary_key_lookup_binary_result() noexcept {
}


MDTrieShard_primary_key_lookup_binary_presult::~MDTrieShard_primary_key_lookup_binary_presult() noexcept {
}


MDTrieShard_get_size_args::~MDTrieShard_get_size_args() noexcept {
}


MDTrieShard_get_size_pargs::~MDTrieShard_get_size_pargs() noexcept {
}


MDTrieShard_get_size_result::~MDTrieShard_get_size_result() noexcept {
}


MDTrieShard_get_size_presult::~MDTrieShard_get_size_presult() noexcept {
}


MDTrieShard_clear_trie_args::~MDTrieShard_clear_trie_args() noexcept {
}


MDTrieShard_clear_trie_pargs::~MDTrieShard_clear_trie_pargs() noexcept {
}


MDTrieShard_clear_trie_result::~MDTrieShard_clear_trie_result() noexcept {
}


MDTrieShard_clear_trie_presult::~MDTrieShard_clear_trie_presult() noexcept {
}


MDTrieShard_get_insert_latency_args::~MDTrieShard_get_insert_latency_args() noexcept {
}


MDTrieShard_get_insert_latency_pargs::~MDTrieShard_get_insert_latency_pargs() noexcept {
}


MDTrieShard_get_insert_latency_result::~MDTrieShard_get_insert_latency_result() noexcept {
}


MDTrieShard_get_insert_latency_presult::~MDTrieShard_get_insert_latency_presult() noexcept {
}


MDTrieShard_get_lookup_latency_args::~MDTrieShard_get_lookup_latency_args() noexcept {
}


MDTrieShard_get_lookup_latency_pargs::~MDTrieShard_get_lookup_latency_pargs() noexcept {
}


MDTrieShard_get_lookup_latency_result::~MDTrieShard_get_lookup_latency_result() noexcept {
}


MDTrieShard_get_lookup_latency_presult::~MDTrieShard_get_lookup_latency_presult() noexcept {
}



