/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MDTrieShard_H
#define MDTrieShard_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "rpc_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MDTrieShardIf {
 public:
  virtual ~MDTrieShardIf() {}
  virtual void ping() = 0;
  virtual int32_t add(const int32_t num1, const int32_t num2) = 0;
  virtual void insert_trie(const std::vector<int32_t> & point, const int32_t length) = 0;
};

class MDTrieShardIfFactory {
 public:
  typedef MDTrieShardIf Handler;

  virtual ~MDTrieShardIfFactory() {}

  virtual MDTrieShardIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MDTrieShardIf* /* handler */) = 0;
};

class MDTrieShardIfSingletonFactory : virtual public MDTrieShardIfFactory {
 public:
  MDTrieShardIfSingletonFactory(const ::std::shared_ptr<MDTrieShardIf>& iface) : iface_(iface) {}
  virtual ~MDTrieShardIfSingletonFactory() {}

  virtual MDTrieShardIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MDTrieShardIf* /* handler */) {}

 protected:
  ::std::shared_ptr<MDTrieShardIf> iface_;
};

class MDTrieShardNull : virtual public MDTrieShardIf {
 public:
  virtual ~MDTrieShardNull() {}
  void ping() {
    return;
  }
  int32_t add(const int32_t /* num1 */, const int32_t /* num2 */) {
    int32_t _return = 0;
    return _return;
  }
  void insert_trie(const std::vector<int32_t> & /* point */, const int32_t /* length */) {
    return;
  }
};


class MDTrieShard_ping_args {
 public:

  MDTrieShard_ping_args(const MDTrieShard_ping_args&);
  MDTrieShard_ping_args& operator=(const MDTrieShard_ping_args&);
  MDTrieShard_ping_args() {
  }

  virtual ~MDTrieShard_ping_args() noexcept;

  bool operator == (const MDTrieShard_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MDTrieShard_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MDTrieShard_ping_args & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_ping_pargs {
 public:


  virtual ~MDTrieShard_ping_pargs() noexcept;

  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_ping_result {
 public:

  MDTrieShard_ping_result(const MDTrieShard_ping_result&);
  MDTrieShard_ping_result& operator=(const MDTrieShard_ping_result&);
  MDTrieShard_ping_result() {
  }

  virtual ~MDTrieShard_ping_result() noexcept;

  bool operator == (const MDTrieShard_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MDTrieShard_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MDTrieShard_ping_result & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_ping_presult {
 public:


  virtual ~MDTrieShard_ping_presult() noexcept;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);

};

typedef struct _MDTrieShard_add_args__isset {
  _MDTrieShard_add_args__isset() : num1(false), num2(false) {}
  bool num1 :1;
  bool num2 :1;
} _MDTrieShard_add_args__isset;

class MDTrieShard_add_args {
 public:

  MDTrieShard_add_args(const MDTrieShard_add_args&);
  MDTrieShard_add_args& operator=(const MDTrieShard_add_args&);
  MDTrieShard_add_args() : num1(0), num2(0) {
  }

  virtual ~MDTrieShard_add_args() noexcept;
  int32_t num1;
  int32_t num2;

  _MDTrieShard_add_args__isset __isset;

  void __set_num1(const int32_t val);

  void __set_num2(const int32_t val);

  bool operator == (const MDTrieShard_add_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const MDTrieShard_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MDTrieShard_add_args & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_add_pargs {
 public:


  virtual ~MDTrieShard_add_pargs() noexcept;
  const int32_t* num1;
  const int32_t* num2;

  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _MDTrieShard_add_result__isset {
  _MDTrieShard_add_result__isset() : success(false) {}
  bool success :1;
} _MDTrieShard_add_result__isset;

class MDTrieShard_add_result {
 public:

  MDTrieShard_add_result(const MDTrieShard_add_result&);
  MDTrieShard_add_result& operator=(const MDTrieShard_add_result&);
  MDTrieShard_add_result() : success(0) {
  }

  virtual ~MDTrieShard_add_result() noexcept;
  int32_t success;

  _MDTrieShard_add_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const MDTrieShard_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MDTrieShard_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MDTrieShard_add_result & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _MDTrieShard_add_presult__isset {
  _MDTrieShard_add_presult__isset() : success(false) {}
  bool success :1;
} _MDTrieShard_add_presult__isset;

class MDTrieShard_add_presult {
 public:


  virtual ~MDTrieShard_add_presult() noexcept;
  int32_t* success;

  _MDTrieShard_add_presult__isset __isset;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);

};

typedef struct _MDTrieShard_insert_trie_args__isset {
  _MDTrieShard_insert_trie_args__isset() : point(false), length(false) {}
  bool point :1;
  bool length :1;
} _MDTrieShard_insert_trie_args__isset;

class MDTrieShard_insert_trie_args {
 public:

  MDTrieShard_insert_trie_args(const MDTrieShard_insert_trie_args&);
  MDTrieShard_insert_trie_args& operator=(const MDTrieShard_insert_trie_args&);
  MDTrieShard_insert_trie_args() : length(0) {
  }

  virtual ~MDTrieShard_insert_trie_args() noexcept;
  std::vector<int32_t>  point;
  int32_t length;

  _MDTrieShard_insert_trie_args__isset __isset;

  void __set_point(const std::vector<int32_t> & val);

  void __set_length(const int32_t val);

  bool operator == (const MDTrieShard_insert_trie_args & rhs) const
  {
    if (!(point == rhs.point))
      return false;
    if (!(length == rhs.length))
      return false;
    return true;
  }
  bool operator != (const MDTrieShard_insert_trie_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MDTrieShard_insert_trie_args & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_insert_trie_pargs {
 public:


  virtual ~MDTrieShard_insert_trie_pargs() noexcept;
  const std::vector<int32_t> * point;
  const int32_t* length;

  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_insert_trie_result {
 public:

  MDTrieShard_insert_trie_result(const MDTrieShard_insert_trie_result&);
  MDTrieShard_insert_trie_result& operator=(const MDTrieShard_insert_trie_result&);
  MDTrieShard_insert_trie_result() {
  }

  virtual ~MDTrieShard_insert_trie_result() noexcept;

  bool operator == (const MDTrieShard_insert_trie_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MDTrieShard_insert_trie_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MDTrieShard_insert_trie_result & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class MDTrieShard_insert_trie_presult {
 public:


  virtual ~MDTrieShard_insert_trie_presult() noexcept;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);

};

template <class Protocol_>
class MDTrieShardClientT : virtual public MDTrieShardIf {
 public:
  MDTrieShardClientT(std::shared_ptr< Protocol_> prot) {
    setProtocolT(prot);
  }
  MDTrieShardClientT(std::shared_ptr< Protocol_> iprot, std::shared_ptr< Protocol_> oprot) {
    setProtocolT(iprot,oprot);
  }
 private:
  void setProtocolT(std::shared_ptr< Protocol_> prot) {
  setProtocolT(prot,prot);
  }
  void setProtocolT(std::shared_ptr< Protocol_> iprot, std::shared_ptr< Protocol_> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return this->piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return this->poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  int32_t add(const int32_t num1, const int32_t num2);
  void send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add();
  void insert_trie(const std::vector<int32_t> & point, const int32_t length);
  void send_insert_trie(const std::vector<int32_t> & point, const int32_t length);
  void recv_insert_trie();
 protected:
  std::shared_ptr< Protocol_> piprot_;
  std::shared_ptr< Protocol_> poprot_;
  Protocol_* iprot_;
  Protocol_* oprot_;
};

typedef MDTrieShardClientT< ::apache::thrift::protocol::TProtocol> MDTrieShardClient;

template <class Protocol_>
class MDTrieShardProcessorT : public ::apache::thrift::TDispatchProcessorT<Protocol_> {
 protected:
  ::std::shared_ptr<MDTrieShardIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
  virtual bool dispatchCallTemplated(Protocol_* iprot, Protocol_* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MDTrieShardProcessorT::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef void (MDTrieShardProcessorT::*SpecializedProcessFunction)(int32_t, Protocol_*, Protocol_*, void*);
  struct ProcessFunctions {
    ProcessFunction generic;
    SpecializedProcessFunction specialized;
    ProcessFunctions(ProcessFunction g, SpecializedProcessFunction s) :
      generic(g),
      specialized(s) {}
    ProcessFunctions() : generic(nullptr), specialized(nullptr) {}
  };
  typedef std::map<std::string, ProcessFunctions> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ping(int32_t seqid, Protocol_* iprot, Protocol_* oprot, void* callContext);
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_add(int32_t seqid, Protocol_* iprot, Protocol_* oprot, void* callContext);
  void process_insert_trie(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_insert_trie(int32_t seqid, Protocol_* iprot, Protocol_* oprot, void* callContext);
 public:
  MDTrieShardProcessorT(::std::shared_ptr<MDTrieShardIf> iface) :
    iface_(iface) {
    processMap_["ping"] = ProcessFunctions(
      &MDTrieShardProcessorT::process_ping,
      &MDTrieShardProcessorT::process_ping);
    processMap_["add"] = ProcessFunctions(
      &MDTrieShardProcessorT::process_add,
      &MDTrieShardProcessorT::process_add);
    processMap_["insert_trie"] = ProcessFunctions(
      &MDTrieShardProcessorT::process_insert_trie,
      &MDTrieShardProcessorT::process_insert_trie);
  }

  virtual ~MDTrieShardProcessorT() {}
};

typedef MDTrieShardProcessorT< ::apache::thrift::protocol::TDummyProtocol > MDTrieShardProcessor;

template <class Protocol_>
class MDTrieShardProcessorFactoryT : public ::apache::thrift::TProcessorFactory {
 public:
  MDTrieShardProcessorFactoryT(const ::std::shared_ptr< MDTrieShardIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< MDTrieShardIfFactory > handlerFactory_;
};

typedef MDTrieShardProcessorFactoryT< ::apache::thrift::protocol::TDummyProtocol > MDTrieShardProcessorFactory;

class MDTrieShardMultiface : virtual public MDTrieShardIf {
 public:
  MDTrieShardMultiface(std::vector<std::shared_ptr<MDTrieShardIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MDTrieShardMultiface() {}
 protected:
  std::vector<std::shared_ptr<MDTrieShardIf> > ifaces_;
  MDTrieShardMultiface() {}
  void add(::std::shared_ptr<MDTrieShardIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  int32_t add(const int32_t num1, const int32_t num2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(num1, num2);
    }
    return ifaces_[i]->add(num1, num2);
  }

  void insert_trie(const std::vector<int32_t> & point, const int32_t length) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->insert_trie(point, length);
    }
    ifaces_[i]->insert_trie(point, length);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
template <class Protocol_>
class MDTrieShardConcurrentClientT : virtual public MDTrieShardIf {
 public:
  MDTrieShardConcurrentClientT(std::shared_ptr< Protocol_> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocolT(prot);
  }
  MDTrieShardConcurrentClientT(std::shared_ptr< Protocol_> iprot, std::shared_ptr< Protocol_> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocolT(iprot,oprot);
  }
 private:
  void setProtocolT(std::shared_ptr< Protocol_> prot) {
  setProtocolT(prot,prot);
  }
  void setProtocolT(std::shared_ptr< Protocol_> iprot, std::shared_ptr< Protocol_> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return this->piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return this->poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  int32_t add(const int32_t num1, const int32_t num2);
  int32_t send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add(const int32_t seqid);
  void insert_trie(const std::vector<int32_t> & point, const int32_t length);
  int32_t send_insert_trie(const std::vector<int32_t> & point, const int32_t length);
  void recv_insert_trie(const int32_t seqid);
 protected:
  std::shared_ptr< Protocol_> piprot_;
  std::shared_ptr< Protocol_> poprot_;
  Protocol_* iprot_;
  Protocol_* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

typedef MDTrieShardConcurrentClientT< ::apache::thrift::protocol::TProtocol> MDTrieShardConcurrentClient;

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#include "MDTrieShard.tcc"
#include "rpc_types.tcc"

#endif
