/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MDTrieShard.h"
#include "MDTrieShard.tcc"




MDTrieShard_get_args::~MDTrieShard_get_args() noexcept {
}


MDTrieShard_get_pargs::~MDTrieShard_get_pargs() noexcept {
}


MDTrieShard_get_result::~MDTrieShard_get_result() noexcept {
}


MDTrieShard_get_presult::~MDTrieShard_get_presult() noexcept {
}



