/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rpc_TYPES_TCC
#define rpc_TYPES_TCC

#include "shared_types.tcc"
#include "rpc_types.h"





#endif
