/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SharedService.h"
#include "SharedService.tcc"




SharedService_getStruct_args::~SharedService_getStruct_args() noexcept {
}


SharedService_getStruct_pargs::~SharedService_getStruct_pargs() noexcept {
}


SharedService_getStruct_result::~SharedService_getStruct_result() noexcept {
}


SharedService_getStruct_presult::~SharedService_getStruct_presult() noexcept {
}



